In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

* Crie um array NumPy com 1000000 e uma lista com 1000000. 
* Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
* Qual objeto oferece melhor performance, array NumPy ou lista?


In [1]:
import pandas as pd
import numpy as np

In [5]:
"""array"""
a = np.arange(1000000)
print(a)

[     0      1      2 ... 999997 999998 999999]


In [6]:
"""lista"""
l = [l for l in range(1000000)]
#l = list(range(1000000))
#imprime os primeiros elementos
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [9]:

#multiplicando o array e a lista

%time a1 = a * 2
#print(a1)



CPU times: user 6.06 ms, sys: 467 µs, total: 6.52 ms
Wall time: 5 ms


In [8]:
%time l1 = map(lambda x:x * 2, l)
list(l1)

CPU times: user 10 µs, sys: 1 µs, total: 11 µs
Wall time: 17.2 µs


[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

 ## Conclui-se então que
 utilizando map e lambda para multiplicar a lista por 2 tem melhor performace

### Exercício 2

In [13]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
a = np.arange(1,11)*2

a[5:9] = 0
a

array([ 2,  4,  6,  8, 10,  0,  0,  0,  0, 20])

### Exercício 3

In [39]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
# A 3D array (two stacked 2D arrays)// dois arrays 2D dentro
c = np.array([ [[0,  1,  2],  
                [ 10, 12, 13]],
                [[100, 101, 102],
                [110, 112, 113]]])

print(c.shape)

#dimensão 0
c[0, ...]
#dimensão 1
c[1, ...]

(2, 2, 3)


array([[100, 101, 102],
       [110, 112, 113]])

### Exercício 4

In [51]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

#cria matriz
matriz = np.array([[1,2,3], [3,4,5], [6,7,8]])

#elementos da 3º linha
print("3º linha")
print(matriz[2])
    
    
#elementos da 1º e 2º linhas
print("1º linha e 2º linha")
for a in matriz[:2]:
    print(a)


##elementos da 2º e 3º linhas
print("2º linha e 3º linha")
for a in matriz[1:]:
    print(a)

3º linha
[6 7 8]
1º linha e 2º linha
[1 2 3]
[3 4 5]
2º linha e 3º linha
[3 4 5]
[6 7 8]


### Exercício 5

In [60]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))

#utiliza a função Numpy transpose()
arr = arr.transpose()
arr

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [61]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

for i in range(len(cond)):
    if cond[i]:
        print(xarr[i])
    else:
        print(yarr[i])

1.1
2.2
1.3
1.4
2.5


### Exercício 7

In [64]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

#https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-save-and-load-numpy-objects
a = np.arange(1,11)

np.save("Array.npy", a)

b = np.load("Array.npy")

print(b)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercício 8

In [71]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

obj1 = obj.drop_duplicates() 
print(list(obj1))


['c', 'a', 'd', 'b']


# Fim